### ISSUE TITLE
save_path error

### ISSUE THREAD

**Issue by DemonTamer534** [NickBrisebois/DiscordChatAI-GPT2#2] opened 2021-01-13 04:59 UTC
Everytime i launch the bot it gives me the following error:
File "C:\Users\(my username)\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

And i'm not sure if it has to do with this, but everytime the bot triggers it just types for around 10 seconds and then just stops without sending anything. just in case, the chat.txt format looked like this:
MESSAGE_1
MESSAGE_2
MESSAGE_3

**Comment by NickBrisebois** [comment] 2021-01-14 20:05
What's the command you're using to run the script? Are you using the Docker?

**Comment by DemonTamer534** [comment] 2021-01-14 20:08
I'm just using "cd C:\Development\DiscordChatAI-GPT2-master
python3 main.py --token (my bot's token)" in powershell

**Comment by NickBrisebois** [comment] 2021-01-14 21:12
You need to run ```python3 main.py --genmodel``` first to generate the GPT2 models first before running that command. 

Also when it types for 10 seconds or so then just stops, its usually because something went wrong in the script. My error reporting is lacking to say the least haha.

**Comment by DemonTamer534** [comment] 2021-01-14 21:38
Oh i did in fact make a model first, i had a 100k line .txt document collected from the chats in my server by my previous bot, and when i generated the model it also just said something about not being able to load save_path but aside from that not much looked weird

**Comment by NickBrisebois** [comment] 2021-01-17 19:53
Huh, that's weird. I'll see if I can reproduce the issue

**Comment by ghost** [comment] 2021-02-08 23:43
I have the same issue.

**Comment by NickBrisebois** [comment] 2021-02-28 18:39
Sorry for the late response, been pretty busy with work and life but i'll see if I can fix it now

**Comment by NickBrisebois** [comment] 2021-02-28 19:37
Hi @DemonTamer534 and @atorsvn, the issue is fixed in the latest commit. It was an issue with the example docker-compose linking the "checkpoints" folder instead of "checkpoint"

**Comment by NickBrisebois** [comment] 2021-02-28 20:39
Nevermind, it's still broken

**Comment by NickBrisebois** [comment] 2021-02-28 21:17
The issue is because you did not train your bot long enough. It needs to reach 1000 (now 100 in latest update) learning cycles before it makes a save point.

**Closed as completed by NickBrisebois** 2021-02-28 21:17 UTC
Labels: bug
